### ISSUE TITLE
Add Prominent Link to Yomichan Migration

### ISSUE THREAD

**Issue by MarvNC** [yomidevs/yomitan-wiki#51]
As there is still an extremely large base of Yomichan users, I think we could have a button or something linking to the migration page on the homepage.

https://yomitan.wiki/other/yomichan-migration/

**Comment by jamesmaa** [comment]
> As there is still an extremely large base of Yomichan users

What is your basis of this observation? It runs against my own assumptions

**Comment by MarvNC** [comment]
No doubt it's in decline, but you'd be surprised how many people just don't bother. I think it'd be worth addressing still with the incoming forced deprecation of mv2.

**Comment by MarvNC** [comment]
Resolved by #58
