### ISSUE TITLE
Fix warning label

### ISSUE THREAD

**Issue by koiyakiya** [yomidevs/yomitan-wiki#69]
![Screenshot_20241021_085750_Chrome.jpg](https://github.com/user-attachments/assets/f2226d04-b106-43db-b6f1-79df65db67b1)

`!!! warning This feature is experimental!`

Does not display as actual warning tip box thing yeah

Probably good first issue too

**Comment by jamesmaa** [comment]
https://github.com/yomidevs/yomitan-wiki/commit/384085da7b39034b6b96ffe358ce5fb1e40954e5 fixed
